### ISSUE TITLE
Cookie notification bar is empty

### ISSUE THREAD

**Issue by marceldegraaf** [segmentio/consent-manager#35] opened 2019-05-08 07:59 UTC
We're trying to set up Segment's Consent Manager (the standalone version) to show our users a cookie notification and to let them manage their tracking preferences.

We're following the documentation from the Github readme: https://github.com/segmentio/consent-manager#standalone-script

This is the super simple HTML page we're testing with: https://gist.github.com/marceldegraaf/e2c490c3f3db11f41db681bab2c12b4f

Unfortunately this only renders an empty `<div></div>` in the target container, and does not show the cookie notification. The Consent Manager popup does open if we call `consentManager.openConsentManager()` from the developer console, and we see no errors/warnings on the developer console.

Screenshots:
- https://marceldegraaf.net/snaps/wbzm36j5ev.png
- https://marceldegraaf.net/snaps/0hqhrdtyhb.png

Are we missing some configuration here, or is this a bug in the Consent Manager?

**Comment by discovrbookings** [comment] 2019-05-14 01:29
We too had this issue and not entirely sure of the cause but our workspace had multiple website sources. Removing all but one had the Consent Manager working as intended.

If this is also the case with your issues, have you any idea why this may be? Or how it could be fixed?

**Comment by Nbennett650** [comment] 2019-07-01 20:46
Did you figure this out?

**Comment by marceldegraaf** [comment] 2019-07-02 08:23
Nope, we ended up rolling our own cookie bar implementation because we ran into too much trouble with the Segment one.

**Comment by Uysim** [comment] 2019-08-12 14:27
Anyone has this fixed? I got the same problem

**Comment by discovrbookings** [comment] 2019-08-12 14:30
For us it seemed that we could only have a single source and it had to contain a destination. I assume that without these, the consent bar had no reason to display as no destinations were using cookies or implemented script into the browser.

**Comment by Uysim** [comment] 2019-08-12 14:44
@discovrbookings I try to add source from javascript and destination to slack. But no matter what it is not showing anything

**Comment by discovrbookings** [comment] 2019-08-12 14:56
@Uysim Are you receiving events in the debug of the source? Also, does the Segment script show up in your `<head>`. We did find that it wasn't immediately available and coming back later it was there. Also, clear your cookies in browser. This make jolt the consent manager to work.

**Comment by Uysim** [comment] 2019-08-12 15:02
```html
<style type="text/css">
  #consent-container {
    position: fixed;
    left: 0;
    right: 0;
    bottom: 0;
    z-index: 100;
  }
</style>
<div id="consent-container"></div>


<!-- footer --->
<script>
  !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t,e){var n=document.createElement("script");n.type="text/javascript";n.async=!0;n.src="https://cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(n,a);analytics._loadOptions=e};analytics.SNIPPET_VERSION="4.1.0";
  analytics.load("WRITE_KEY");
  analytics.page();
  }}();
</script>
<script
  src="https://unpkg.com/@segment/consent-manager@1.2.0/standalone/consent-manager.js"
  crossorigin="anonymous"
  defer
  data-container="#consent-container"
  data-writeKey="WRITE_KEY"
  data-bannerContent="We use cookies (and other similar technologies) to collect data to improve your experience on our site."
  data-bannerSubContent="You can change your preferences at any time."
  data-preferencesDialogTitle="Website Data Collection Preferences"
  data-preferencesDialogContent="We use data collected by cookies and JavaScript libraries to improve your browsing experience, analyze site traffic, deliver personalized advertisements, and increase the overall performance of our site."
  data-cancelDialogTitle="Are you sure you want to cancel?"
  data-cancelDialogContent="Your preferences have not been saved. By continuing to use our website, you՚re agreeing to our Website Data Collection Policy."
></script>
```

@discovrbookings above is my code. I use private browser so there is no cookies but It still not show anything inside `consent-container` it created an empty div

**Comment by discovrbookings** [comment] 2019-08-12 15:09
You do need to remove `analytics.load("YOUR_WRITE_KEY");` from your script as this is injected by the consent manager component.

**Comment by discovrbookings** [comment] 2019-08-12 15:10
@Uysim or is your code, already compiled? and that is the HTML source?

**Comment by Uysim** [comment] 2019-08-12 15:19
@discovrbookings what do you mean compiled? that is the html code.

**Comment by discovrbookings** [comment] 2019-08-12 15:23
@Uysim I meant are you using Angular, React, etc and your code is static content in your public folder or is it the HTML source from the browser?

**Comment by Uysim** [comment] 2019-08-18 05:29
@discovrbookings thank for you help. But my problem fix after mailing with support and he ask me to wait 5 or 10 minutes.

**Comment by rpholdaway** [comment] 2020-10-19 12:47
It was fixed in my case by adding a destination to the source (then waiting about 90 mins for it to take effect).

**Comment by felipe-najson-ntf** [comment] 2021-09-14 14:39
Hi everyone, sorry for the late reply. The standalone version is working correctly in the current version of consent manager, the documentation has been updated also for a clearer installation.
Here I leave a link.
https://github.com/segmentio/consent-manager#standalone-script

If you continue to have problems feel free to open another issue. On the other hand, I will close this issue since it was resolved.

Segment team.

**Closed** 2021-09-15 17:45 UTC
