### ISSUE TITLE
Vue.js support

### ISSUE THREAD

**Issue by morrislaptop** [segmentio/consent-manager#75] opened 2020-02-14 16:02 UTC
Are there any guides on how to integrate this with Vue? (We don't use React)

**Comment by jrpersico** [comment] 2020-04-27 20:07
Have you found a solution to integrate it with vue.js ?

**Comment by felipe-najson** [comment] 2021-09-03 13:33
Hi everyone! Sorry for the late reply. I will be giving an update on this in the next few days.

On the other hand, I will close this issue and continue the discussion in another issue since it is duplicated. Thank you for your contribution!
Duplicate of #106 

Segment Team.

**Comment by felipe-najson-ntf** [comment] 2021-09-03 13:42
Hi everyone! Sorry for the late reply. I will be giving an update on this in the next few days.

On the other hand, I will close this issue and continue the discussion in another issue since it is duplicated. Thank you for your contribution!  
Duplicate of #106

Segment Team.

**Closed** 2021-09-07 14:52 UTC
