### ISSUE TITLE
Localization?

### ISSUE THREAD

**Issue by jeremybdk** [segmentio/consent-manager#27] opened 2018-08-29 15:09 UTC
Hello,
Do you plan to offer a localized version of the consent manager?
I would love to help translate it into french but I see that the text is currently hardcoded into the javascript. Any plans to change this?

Best,

**Comment by nettofarah** [comment] 2018-09-06 19:10
hey, @jeremybdk 
Thanks for offering to help.

We unfortunately cannot be liable for translations that have not been thoroughly reviewed by our lawyers and counseling, since the folks involved in maintaining this codebase are just engineers and not people with significant legal and foreign language experience.

There are still solutions for your problem though :)

I would recommend checking out the custom react components defined here:
https://github.com/segmentio/consent-manager#consentmanagerbuilder

By using those components you should have access to all the moving pieces and be able to build a user experience that makes sense for your product.

You can see some examples here of how the implementation could look like: https://github.com/segmentio/consent-manager/tree/master/tools/stories

**Comment by jeremybdk** [comment] 2018-09-08 20:39
I totally understand, would it be possible to make all the text in the consent manager customizable? It might solve the issue as english would be the default unless you add a variable with your translation.

**Comment by otherjustin** [comment] 2020-01-03 17:57
I would second this request. You guys have done a great job making a lot of it accessible, but, for example, seemingly none of the text in the "settings table" can be changed. It would help a lot to be able to do this!

**Comment by felipe-najson-ntf** [comment] 2021-09-02 17:42
Hi everyone! I want to emphasize that most of the content is customizable in the current version of consent-manager as detailed here https://github.com/segmentio/consent-manager#bannercontent.
I will be working these days to make the "settings table" customizable as well.

We will close this issue and continue the discussion in another issue since it is duplicated. Thank you for your contribution! 
Duplicate of #137 

Segment Team.

**Comment by nd4p90x** [comment] 2021-09-02 18:14
Please feel free to follow along with the new issues as @felipe-najson-ntf suggests.  Thank you

**Closed by nd4p90x** 2021-09-02 18:14 UTC

**Comment by agracia-foticos** [comment] 2024-01-19 11:30
we are using standalone version... How i can use Localization for this case??

Thanks in advance
