### ISSUE TITLE
Warning: componentWillMount has been renamed, and is not recommended for use.

### ISSUE THREAD

**Issue by Dezzymei** [segmentio/consent-manager#135] opened 2021-03-10 13:48 UTC
Using React 17.x I get this error whenever I use the consent manager.

**Comment by felipe-najson-ntf** [comment] 2021-09-17 16:57
Hi @Dezzymei, the issue still persists. Apparently the warning is not due to Consent Manager by itself but to a third-party library that uses this method. I will be investigating these days to update that dependency in order to remove the warning. I will keep you updated.

Thanks, segment team.

**Comment by felipe-najson-ntf** [comment] 2021-09-22 14:55
Update. @Dezzymei 

As we suspected the problem is in a third party library called "react-emotion". For my research we would need to migrate to "@emotion-styled" as documented here.
https://www.npmjs.com/package/react-emotion
Which is not straightforward. At the moment it is a warning so we will lower the priority of this issue and discuss with the team what decision to make.

Thanks for your contribution. Segment team

**Closed as completed** 2021-10-14 20:59 UTC

**Comment by Dezzymei** [comment] 2022-03-29 16:16
I have created a PR for this: https://github.com/segmentio/consent-manager/pull/216
