### ISSUE TITLE
Tracking starts immediately after closing banner with closeBehavior="deny"

### ISSUE THREAD

**Issue by lopno** [segmentio/consent-manager#81] opened 2020-03-11 10:04 UTC
When using the standalone script tracking starts immediately after closing the banner no matter what the `closeBehavior` is set to.
I've tried both `deny` and `dismiss` but tracking starts immediately after closing the banner no matter which option is set.

The React component respects the option, so the issue is only in the standalone script.

**Comment by felipe-najson** [comment] 2021-09-03 13:38
Hello @lopno. Sorry for the late reply. I will be working on this problem in the next few weeks, I will be giving an update on another more recent issue since this one is duplicated.

I will close this issue and continue the discussion there. 
Duplicate of #104 

Segment Team.

**Comment by felipe-najson-ntf** [comment] 2021-09-03 13:43
Hello @lopno. Sorry for the late reply. I will be working on this problem in the next few weeks, I will be giving an update on another more recent issue since this one is duplicated.

I will close this issue and continue the discussion there. 
Duplicate of #104

Segment Team.

**Closed** 2021-09-07 14:53 UTC
Labels: duplicate
