### ISSUE TITLE
Using consent-manager causes reload

### ISSUE THREAD

**Issue by thoreyjona** [segmentio/consent-manager#10] opened 2018-05-25 15:57 UTC
I have a React Web Application and I am using consent manager. If I go to a new page within my application it causes a reload of the page which I don't want. If I comment out the consent manager code this does not happen. Is there some way to stop the page from reloading?

I'm using it this way:

```javascript
<ConsentManager
  writeKey={SEGMENT_WRITE_KEY}
  shouldRequireConsent={inEU}
  bannerContent={bannerContent}
  preferencesDialogTitle={preferencesDialogTitle}
  preferencesDialogContent={preferencesDialogContent}
  cancelDialogTitle={cancelDialogTitle}
  cancelDialogContent={cancelDialogContent}
  bannerBackgroundColor={'rgba(31,29,29,.15)'}
  bannerTextColor={'rgba(31,29,29,1)'}
/>
```

**Comment by nettofarah** [comment] 2018-05-25 21:19
@jfmaggie Feel free to investigate this issue too

**Comment by Rowno** [comment] 2018-05-25 22:00
I believe what's happening is that the ConsentManager is getting unmounted/remounted between your page transitions which is causing the reload. We reload the page if analytics.js has already been initialised to make sure the user's preferences take affect. 

I can disable the reload functionality on mount, but the list of destinations will still be re-downloaded on each page transition for you.

**Comment by hlodver** [comment] 2018-05-29 10:36
Hi guys.. I am working with @thoreyjona 

First of all, thanks for the fast replies and open sourcing this tool!  In our React application we are using different components for each route but reuse a common one where we loaded the CM (ConsentManager).  Using the standalone script approach would have avoided this issue. For now we decided to conditionally load the CM based on the cookie set by it ('tracking-preferences') or if the user wished to make changes (also if we add new integrations).

If you plan on supporting this tool onward I think it would be possible to do minor changes to support better different types of React Applications by caching the destination list (use the cookie) and avoiding reloads (If the cookie is set you can know if CM was run).

**Comment by ostrgard** [comment] 2018-08-27 08:27
I love this idea and Segment's general stance on privacy/GDPR. Thanks for open sourcing this!

Which issues does the reload on mount solve? For a component, I think this is very unexpected behavior. You generally shouldn't have to worry about a certain component being remounted will cause a window reload.  At least I think this should be done in a more intelligent fashion, rather than "just to make sure" (this might be an understatement).

My issue as of right now (besides spending my first implementation hour understanding these, at first glance seemingly random, reloads) is that hot reloading is broken.

I agree with @hlodver's suggestion by using a cached destination list. I'd like to hear your thoughts on that.

**Comment by nettofarah** [comment] 2019-02-19 17:26
Hi, everyone.
I'm sorry for the late response here.

Here's the code we use to load analytics.js: https://github.com/segmentio/consent-manager/blob/49d1ed58b70ad9a59ac5ea54f7b988eac6e38dc2/src/consent-manager-builder/analytics.js

The reason why you're seeing page reloads is because analytics.js is being loaded *before* the consent manager, which means tracking has already occurred (which basically renders consent management useless).

I can think of a few possible solutions to the problem:

1. (client change) You should always make sure you're loading the consent manager before `analytics.js` is loaded. i.e. make sure to remove `analytics.load("YOUR_WRITE_KEY")` from your ajs snippet.

2. (client change) Make sure you're only ever mounting the consent manager once, otherwise you'll keep re-executing that snippet of code I pasted.

3. (consent manager) We could make it so you could pass an option to not reload the page in case analytics.js is detected as loaded.

I'm ok with changing the consent manager to accommodate for *3*, but I'll probably need to check with our legal team first to see if there's possibly any liability in doing so.

How does that sound?

**Comment by ahallora** [comment] 2019-03-25 10:33
I experienced the same issue with reloading in my Reactjs application on router navigations.

The solution was to move my [ConsentManager-component](https://github.com/segmentio/consent-manager#example) from my `footer.js` (mounted on every router navigation) to `app.js` (for one-time mounting).

My [segment initialization-script](https://segment.com/docs/sources/website/analytics.js/quickstart/#step-1-copy-the-snippet) was just sitting in `public/index.html` all along with `analytics.load(key)` and `analytics.page()` commented out.

**Comment by jhoffmcd** [comment] 2019-05-24 22:06
Just realized my issue #36 is basically this issue. I'll close mine out, but definitely a pretty jarring and bad UX for the page reload for client side transitions. I think the workaround for this being that you only want the component to render once is fine, but should DEF be documented somewhere up front. Spent a day on this :(

**Comment by motin** [comment] 2020-08-25 08:54
Also affected, using Gatsby. To use the workaround proposed by @ahallora, one needs to use https://www.gatsbyjs.com/docs/browser-apis/#wrapPageElement since there is no app.js in Gatsby.

**Comment by jdahdah** [comment] 2020-11-20 15:49
Is there any way to prevent reloads with this in Gatsby without having to utilize `wrapPageElement`? I'm using [gatsby-plugin-intl](https://github.com/wiziple/gatsby-plugin-intl) and running into tons of issues when I go anywhere near `wrapPageElement`.

**Comment by davebrewer** [comment] 2021-02-23 17:47
wrapPageElement didn't work for us but wrapRootElement did.

**Comment by felipe-najson-ntf** [comment] 2021-09-02 17:52
Hi everyone! I adhere to what @nettofarah says. Verify that you have followed the steps of use correctly to not have problems. In the current version of consent-manager no reload errors have been found. If anyone continues to have problems, feel free to open a new issue.

We will close this issue definitively, thank you for your contribution.
Segment Team.

**Comment by nd4p90x** [comment] 2021-09-02 18:12
Please feel free to re-open this issue or a new one if the issue persists.  Duplicate of newer issue #127 . Thank you

**Closed by nd4p90x** 2021-09-02 18:12 UTC
Labels: bug

**Comment by kwent** [comment] 2021-12-20 05:30
I think like a lot of people i copied the snippet present in https://github.com/segmentio/consent-manager/blob/master/README.md#example-in-nextjs. Really hard to see this is calling `analytics.load` if you do not scroll to the right. After removing that part. It's working as expected.
